### ISSUE TITLE
Template Gallery Review

### ISSUE THREAD

**Issue by delsonting** [AmadeusITGroup/Amadeus-MetaConnect-Flight-Preselection#1]
Your template has been approved and should be available in the gallery to users shortly. Recommendation for template.tpl line 71 to pass data.gtmOnSuccess and data.gtmOnFailure as callbacks on the injectscript call and remove the data.gtmOnSuccess() call on line 74. 

Check out the last line from [sample code](https://developers.google.com/tag-manager/templates/convert-existing-tag#fully_converted_tag
) 

```
const setInWindow = require('setInWindow');
const copyFromWindow = require('copyFromWindow');
const createArgumentsQueue = require('createArgumentsQueue');
const getTimestamp = require('getTimestamp');
const injectScript = require('injectScript');
const trackingId = data.trackingId;

const ga = createArgumentsQueue('ga', 'ga.q');
setInWindow('ga.l', getTimestamp(), false);
ga('create', trackingId, 'auto');
ga('send', 'pageview');
const url = 'https://www.google-analytics.com/analytics.js';
injectScript(url, data.gtmOnSuccess, data.gtmOnFailure, url);
```

**Comment by Bezineb** [comment]
@delsonting Thanks for the code review! It has been updated accordingly.
